- name: Destroy Environment
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy Environment
      azure_rm_resourcegroup:
        name: myResourceGroup
        state: absent
        force: yes
