---
- hosts: localhost
  connection: local
  tasks:
  - vsphere_guest:
      vcenter_hostname: 192.168.220.131
      username: root
      password: vmware
      guest: newvm001
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
      vm_disk:
        disk1:
          size_gb: 16
          type: thin
          datastore: datastore1
          # VMs can be put into folders. The value given here is either the full path
          # to the folder (e.g. production/customerA/lamp) or just the last component
          # of the path (e.g. lamp):
          folder: "datasource1/AnsibleDemo"
      vm_nic:
        nic1:
          type: E1000
          network: VM Network   
		  # you change network: to another name like DMZ
          network_type: standard
      vm_hardware:
        memory_mb: 512
        num_cpus: 1
        osid: RHEL64Guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "datastore1/ISO FILES/rhel-server-7.2-x86_64-dvd.iso"
      esxi:
        datacenter: Converge
        hostname: 192.168.220.130